require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/member_trees", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MemberTree. As you add validations to MemberTree, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MemberTree.create! valid_attributes
      get member_trees_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      member_tree = MemberTree.create! valid_attributes
      get member_tree_url(member_tree)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_member_tree_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      member_tree = MemberTree.create! valid_attributes
      get edit_member_tree_url(member_tree)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MemberTree" do
        expect {
          post member_trees_url, params: { member_tree: valid_attributes }
        }.to change(MemberTree, :count).by(1)
      end

      it "redirects to the created member_tree" do
        post member_trees_url, params: { member_tree: valid_attributes }
        expect(response).to redirect_to(member_tree_url(MemberTree.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MemberTree" do
        expect {
          post member_trees_url, params: { member_tree: invalid_attributes }
        }.to change(MemberTree, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post member_trees_url, params: { member_tree: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested member_tree" do
        member_tree = MemberTree.create! valid_attributes
        patch member_tree_url(member_tree), params: { member_tree: new_attributes }
        member_tree.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the member_tree" do
        member_tree = MemberTree.create! valid_attributes
        patch member_tree_url(member_tree), params: { member_tree: new_attributes }
        member_tree.reload
        expect(response).to redirect_to(member_tree_url(member_tree))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        member_tree = MemberTree.create! valid_attributes
        patch member_tree_url(member_tree), params: { member_tree: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested member_tree" do
      member_tree = MemberTree.create! valid_attributes
      expect {
        delete member_tree_url(member_tree)
      }.to change(MemberTree, :count).by(-1)
    end

    it "redirects to the member_trees list" do
      member_tree = MemberTree.create! valid_attributes
      delete member_tree_url(member_tree)
      expect(response).to redirect_to(member_trees_url)
    end
  end
end
