require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/mentor_assignments", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MentorAssignment. As you add validations to MentorAssignment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MentorAssignment.create! valid_attributes
      get mentor_assignments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      mentor_assignment = MentorAssignment.create! valid_attributes
      get mentor_assignment_url(mentor_assignment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_mentor_assignment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      mentor_assignment = MentorAssignment.create! valid_attributes
      get edit_mentor_assignment_url(mentor_assignment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MentorAssignment" do
        expect {
          post mentor_assignments_url, params: { mentor_assignment: valid_attributes }
        }.to change(MentorAssignment, :count).by(1)
      end

      it "redirects to the created mentor_assignment" do
        post mentor_assignments_url, params: { mentor_assignment: valid_attributes }
        expect(response).to redirect_to(mentor_assignment_url(MentorAssignment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MentorAssignment" do
        expect {
          post mentor_assignments_url, params: { mentor_assignment: invalid_attributes }
        }.to change(MentorAssignment, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post mentor_assignments_url, params: { mentor_assignment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mentor_assignment" do
        mentor_assignment = MentorAssignment.create! valid_attributes
        patch mentor_assignment_url(mentor_assignment), params: { mentor_assignment: new_attributes }
        mentor_assignment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the mentor_assignment" do
        mentor_assignment = MentorAssignment.create! valid_attributes
        patch mentor_assignment_url(mentor_assignment), params: { mentor_assignment: new_attributes }
        mentor_assignment.reload
        expect(response).to redirect_to(mentor_assignment_url(mentor_assignment))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        mentor_assignment = MentorAssignment.create! valid_attributes
        patch mentor_assignment_url(mentor_assignment), params: { mentor_assignment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested mentor_assignment" do
      mentor_assignment = MentorAssignment.create! valid_attributes
      expect {
        delete mentor_assignment_url(mentor_assignment)
      }.to change(MentorAssignment, :count).by(-1)
    end

    it "redirects to the mentor_assignments list" do
      mentor_assignment = MentorAssignment.create! valid_attributes
      delete mentor_assignment_url(mentor_assignment)
      expect(response).to redirect_to(mentor_assignments_url)
    end
  end
end
