# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

mentors = Mentor.create([{ first_name: 'Anna', middle_name: '', last_name: '', 
                        email: '', phone_number: ''},
                        { first_name: 'Noel', middle_name: '', last_name: '', 
                        email: '', phone_number: ''},
                        { first_name: 'Annie B.', middle_name: '', last_name: '', 
                        email: '', phone_number: ''},
                        { first_name: 'Rohan', middle_name: '', last_name: '', 
                        email: '', phone_number: ''},
                        { first_name: 'Annie K.', middle_name: '', last_name: '', 
                        email: '', phone_number: ''},
                        { first_name: 'Sameera', middle_name: '', last_name: '', 
                        email: '', phone_number: ''},
                        { first_name: 'Darin', middle_name: '', last_name: '', 
                        email: '', phone_number: ''},
                        { first_name: 'Tina', middle_name: '', last_name: '', 
                        email: '', phone_number: ''},
                        { first_name: 'Diana', middle_name: '', last_name: '', 
                        email: '', phone_number: ''},
                        { first_name: 'Eliza', middle_name: '', last_name: '', 
                        email: '', phone_number: ''},
                        { first_name: 'Hanna', middle_name: '', last_name: '', 
                        email: '', phone_number: ''},
                        { first_name: 'Jedd', middle_name: '', last_name: '', 
                        email: '', phone_number: ''},
                        { first_name: 'Jack', middle_name: '', last_name: '', 
                        email: '', phone_number: ''},
                        { first_name: 'Vincent', middle_name: '', last_name: '', 
                        email: '', phone_number: ''},
                        { first_name: 'Jae', middle_name: '', last_name: '', 
                        email: '', phone_number: ''},
                        { first_name: 'Newton', middle_name: '', last_name: '', 
                        email: '', phone_number: ''},
                        { first_name: 'Katie', middle_name: '', last_name: '', 
                        email: '', phone_number: ''},
                        { first_name: 'Loris', middle_name: '', last_name: '', 
                        email: '', phone_number: ''},
                        { first_name: 'Krisha', middle_name: '', last_name: '', 
                        email: '', phone_number: ''},
                        { first_name: 'Mariya', middle_name: '', last_name: '', 
                        email: '', phone_number: ''},
                        { first_name: 'Ly', middle_name: '', last_name: '', 
                        email: '', phone_number: ''},
                        { first_name: 'Yna', middle_name: '', last_name: '', 
                        email: '', phone_number: ''}])

mentees = Mentee.create([{ first_name: 'Aarya', middle_name: '', last_name: 'Newasekar',
                        email: '', phone_number: ''},
                        { first_name: 'Caroline', middle_name: '', last_name: 'Fu',
                        email: '', phone_number: ''},
                        { first_name: 'Claire', middle_name: '', last_name: 'Cruz',
                        email: '', phone_number: ''},
                        { first_name: 'Evelyn', middle_name: '', last_name: 'Hsiao',
                        email: '', phone_number: ''},
                        { first_name: 'Pooranie', middle_name: '', last_name: 'SriPrabhakhar',
                        email: '', phone_number: ''},
                        { first_name: 'Rishika', middle_name: '', last_name: 'Chimanji',
                        email: '', phone_number: ''},
                        { first_name: 'Tiffany', middle_name: '', last_name: 'Vu',
                        email: '', phone_number: ''},
                        { first_name: 'Adarsh', middle_name: '', last_name: 'Vadlapatla',
                        email: '', phone_number: ''},
                        { first_name: 'Ana', middle_name: '', last_name: 'Cruz',
                        email: '', phone_number: ''},
                        { first_name: 'Andrew', middle_name: '', last_name: 'Nguyen',
                        email: '', phone_number: ''},
                        { first_name: 'Elizabeth (Lizzy)', middle_name: '', last_name: 'Wang',
                        email: '', phone_number: ''},
                        { first_name: 'Poojitha Sai', middle_name: '', last_name: 'Sajja',
                        email: '', phone_number: ''},
                        { first_name: 'Riya', middle_name: '', last_name: 'Pendse',
                        email: '', phone_number: ''},
                        { first_name: 'Safirah', middle_name: '', last_name: 'Munir',
                        email: '', phone_number: ''},
                        { first_name: 'Emily', middle_name: '', last_name: 'Chang',
                        email: '', phone_number: ''},
                        { first_name: 'Joon', middle_name: '', last_name: 'Cho',
                        email: '', phone_number: ''},
                        { first_name: 'Kinjal ', middle_name: '', last_name: 'Jain',
                        email: '', phone_number: ''},
                        { first_name: 'Leen', middle_name: '', last_name: 'Maknojia',
                        email: '', phone_number: ''},
                        { first_name: 'Suyin ', middle_name: '', last_name: 'Woo',
                        email: '', phone_number: ''},
                        { first_name: 'Vasudha', middle_name: '', last_name: 'Sridhar',
                        email: '', phone_number: ''},
                        { first_name: 'Zion', middle_name: '', last_name: 'Laguna',
                        email: '', phone_number: ''},
                        { first_name: 'Benjamin', middle_name: '', last_name: 'Kelley',
                        email: '', phone_number: ''},
                        { first_name: 'Bryan', middle_name: '', last_name: 'Bui',
                        email: '', phone_number: ''},
                        { first_name: 'Ethan', middle_name: '', last_name: 'Tong',
                        email: '', phone_number: ''},
                        { first_name: 'Inayaa', middle_name: '', last_name: 'Khoja',
                        email: '', phone_number: ''},
                        { first_name: 'Kane', middle_name: '', last_name: 'Dong',
                        email: '', phone_number: ''},
                        { first_name: 'Hannah', middle_name: '', last_name: 'Zhang',
                        email: '', phone_number: ''},
                        { first_name: 'Jude', middle_name: '', last_name: 'Jolly',
                        email: '', phone_number: ''},
                        { first_name: 'Shreyansh ', middle_name: '', last_name: 'Chhalotra',
                        email: '', phone_number: ''},
                        { first_name: 'Haresh', middle_name: '', last_name: 'Raj',
                        email: '', phone_number: ''},
                        { first_name: 'Jennifer', middle_name: '', last_name: 'Nguyen',
                        email: '', phone_number: ''},
                        { first_name: 'Joanne', middle_name: '', last_name: 'Liu',
                        email: '', phone_number: ''},
                        { first_name: 'Kaelan', middle_name: '', last_name: 'Patel',
                        email: '', phone_number: ''},
                        { first_name: 'Keshari', middle_name: '', last_name: 'Rijal',
                        email: '', phone_number: ''},
                        { first_name: 'Megan', middle_name: '', last_name: 'Phan',
                        email: '', phone_number: ''},
                        { first_name: 'Sriram', middle_name: '', last_name: 'Gaddam',
                        email: '', phone_number: ''},
                        { first_name: 'Alianne', middle_name: '', last_name: 'Elmore',
                        email: '', phone_number: ''},
                        { first_name: 'Courtney', middle_name: '', last_name: 'Le',
                        email: '', phone_number: ''},
                        { first_name: 'David', middle_name: '', last_name: 'Wang',
                        email: '', phone_number: ''},
                        { first_name: 'Nhi', middle_name: '', last_name: 'Tran',
                        email: '', phone_number: ''},
                        { first_name: 'Rhea', middle_name: '', last_name: 'Sharma',
                        email: '', phone_number: ''},
                        { first_name: 'Uma', middle_name: '', last_name: 'Uppuloori',
                        email: '', phone_number: ''},
                        { first_name: 'Jeffrey', middle_name: '', last_name: 'Kang',
                        email: '', phone_number: ''},
                        { first_name: 'Caitlin', middle_name: '', last_name: 'Samson',
                        email: '', phone_number: ''},
                        { first_name: 'Hu-jin', middle_name: '', last_name: 'Sonthavong',
                        email: '', phone_number: ''},
                        { first_name: 'Snikitha', middle_name: '', last_name: 'Surishetty',
                        email: '', phone_number: ''},
                        { first_name: 'Dev', middle_name: '', last_name: 'Maisuria',
                        email: '', phone_number: ''},
                        { first_name: 'Isabella', middle_name: '', last_name: 'Mosher',
                        email: '', phone_number: ''},
                        { first_name: 'Kunal', middle_name: '', last_name: 'Jain',
                        email: '', phone_number: ''},
                        { first_name: 'Pranav', middle_name: '', last_name: 'Moogala',
                        email: '', phone_number: ''},
                        { first_name: 'Yaena (michele)', middle_name: '', last_name: 'Hong',
                        email: '', phone_number: ''},
                        { first_name: 'Andrew', middle_name: '', last_name: 'Zheng',
                        email: '', phone_number: ''},
                        { first_name: 'Felix', middle_name: '', last_name: 'Chim',
                        email: '', phone_number: ''},
                        { first_name: 'Isabella', middle_name: '', last_name: 'Vu',
                        email: '', phone_number: ''},
                        { first_name: 'Jaeyeon (Erith)', middle_name: '', last_name: 'Won',
                        email: '', phone_number: ''},
                        { first_name: 'Justin', middle_name: '', last_name: 'Nguyen',
                        email: '', phone_number: ''},
                        { first_name: 'Rohan', middle_name: '', last_name: 'Jain',
                        email: '', phone_number: ''},
                        { first_name: 'Sarah Jessica', middle_name: '', last_name: 'Ward',
                        email: '', phone_number: ''},
                        { first_name: 'Vibhav', middle_name: '', last_name: 'Jaripatke',
                        email: '', phone_number: ''},
                        { first_name: 'Grace', middle_name: '', last_name: 'Ramirez',
                        email: '', phone_number: ''},
                        { first_name: 'Hamzah', middle_name: '', last_name: 'Mir',
                        email: '', phone_number: ''},
                        { first_name: 'Aarya', middle_name: '', last_name: 'Bookseller',
                        email: '', phone_number: ''},
                        { first_name: 'Phoebe', middle_name: '', last_name: 'Surmadi',
                        email: '', phone_number: ''},
                        { first_name: 'Rachna', middle_name: '', last_name: 'Edalur',
                        email: '', phone_number: ''},
                        { first_name: 'Sebastian', middle_name: '', last_name: 'Chu',
                        email: '', phone_number: ''},
                        { first_name: 'Tyler', middle_name: '', last_name: 'Luong',
                        email: '', phone_number: ''},
                        { first_name: 'Aaryaman', middle_name: '', last_name: 'Mummadavarapu',
                        email: '', phone_number: ''},
                        { first_name: 'Athul', middle_name: '', last_name: 'Suresh',
                        email: '', phone_number: ''},
                        { first_name: 'Jenny', middle_name: '', last_name: 'Kim',
                        email: '', phone_number: ''},
                        { first_name: 'Mira', middle_name: '', last_name: 'Shah',
                        email: '', phone_number: ''},
                        { first_name: 'Nutdanai (Jita)', middle_name: '', last_name: 'Jiencharoen',
                        email: '', phone_number: ''},
                        { first_name: 'Riya', middle_name: '', last_name: 'Vellore',
                        email: '', phone_number: ''},
                        { first_name: 'Selina', middle_name: '', last_name: 'Huang',
                        email: '', phone_number: ''},
                        { first_name: 'Ann', middle_name: '', last_name: 'Nguyen',
                        email: '', phone_number: ''},
                        { first_name: 'Brandon ', middle_name: '', last_name: 'Nguyen',
                        email: '', phone_number: ''},
                        { first_name: 'Daniel', middle_name: '', last_name: 'Cho',
                        email: '', phone_number: ''},
                        { first_name: 'Harrison', middle_name: '', last_name: 'Pham',
                        email: '', phone_number: ''},
                        { first_name: 'James', middle_name: '', last_name: 'Hou',
                        email: '', phone_number: ''},
                        { first_name: 'Sreya', middle_name: '', last_name: 'Suresh',
                        email: '', phone_number: ''},
                        { first_name: 'Teresha', middle_name: '', last_name: 'Ferdhousi',
                        email: '', phone_number: ''},
                        { first_name: 'Timothy', middle_name: '', last_name: 'Aing',
                        email: '', phone_number: ''}])

mentor_assignments = MentorAssignment.create([{Mentor_id: 1, Mentee_id: 1, class_year:'2022-2023'},{Mentor_id: 2, Mentee_id: 1, class_year:'2022-2023'},
                                            {Mentor_id: 1, Mentee_id: 2, class_year:'2022-2023'},{Mentor_id: 2, Mentee_id: 2, class_year:'2022-2023'},
                                            {Mentor_id: 1, Mentee_id: 3, class_year:'2022-2023'},{Mentor_id: 2, Mentee_id: 3, class_year:'2022-2023'},
                                            {Mentor_id: 1, Mentee_id: 4, class_year:'2022-2023'},{Mentor_id: 2, Mentee_id: 4, class_year:'2022-2023'},
                                            {Mentor_id: 1, Mentee_id: 5, class_year:'2022-2023'},{Mentor_id: 2, Mentee_id: 5, class_year:'2022-2023'},
                                            {Mentor_id: 1, Mentee_id: 6, class_year:'2022-2023'},{Mentor_id: 2, Mentee_id: 6, class_year:'2022-2023'},
                                            {Mentor_id: 1, Mentee_id: 7, class_year:'2022-2023'},{Mentor_id: 2, Mentee_id: 7, class_year:'2022-2023'},
                                            {Mentor_id: 3, Mentee_id: 8, class_year:'2022-2023'},{Mentor_id: 4, Mentee_id: 8, class_year:'2022-2023'},
                                            {Mentor_id: 3, Mentee_id: 9, class_year:'2022-2023'},{Mentor_id: 4, Mentee_id: 9, class_year:'2022-2023'},
                                            {Mentor_id: 3, Mentee_id: 10, class_year:'2022-2023'},{Mentor_id: 4, Mentee_id: 10, class_year:'2022-2023'},
                                            {Mentor_id: 3, Mentee_id: 11, class_year:'2022-2023'},{Mentor_id: 4, Mentee_id: 11, class_year:'2022-2023'},
                                            {Mentor_id: 3, Mentee_id: 12, class_year:'2022-2023'},{Mentor_id: 4, Mentee_id: 12, class_year:'2022-2023'},
                                            {Mentor_id: 3, Mentee_id: 13, class_year:'2022-2023'},{Mentor_id: 4, Mentee_id: 13, class_year:'2022-2023'},
                                            {Mentor_id: 3, Mentee_id: 14, class_year:'2022-2023'},{Mentor_id: 4, Mentee_id: 14, class_year:'2022-2023'},
                                            {Mentor_id: 5, Mentee_id: 15, class_year:'2022-2023'},{Mentor_id: 6, Mentee_id: 15, class_year:'2022-2023'},
                                            {Mentor_id: 5, Mentee_id: 16, class_year:'2022-2023'},{Mentor_id: 6, Mentee_id: 16, class_year:'2022-2023'},
                                            {Mentor_id: 5, Mentee_id: 17, class_year:'2022-2023'},{Mentor_id: 6, Mentee_id: 17, class_year:'2022-2023'},
                                            {Mentor_id: 5, Mentee_id: 18, class_year:'2022-2023'},{Mentor_id: 6, Mentee_id: 18, class_year:'2022-2023'},
                                            {Mentor_id: 5, Mentee_id: 19, class_year:'2022-2023'},{Mentor_id: 6, Mentee_id: 19, class_year:'2022-2023'},
                                            {Mentor_id: 5, Mentee_id: 20, class_year:'2022-2023'},{Mentor_id: 6, Mentee_id: 20, class_year:'2022-2023'},
                                            {Mentor_id: 5, Mentee_id: 21, class_year:'2022-2023'},{Mentor_id: 6, Mentee_id: 21, class_year:'2022-2023'},
                                            {Mentor_id: 7, Mentee_id: 22, class_year:'2022-2023'},{Mentor_id: 8, Mentee_id: 22, class_year:'2022-2023'},
                                            {Mentor_id: 7, Mentee_id: 23, class_year:'2022-2023'},{Mentor_id: 8, Mentee_id: 23, class_year:'2022-2023'},
                                            {Mentor_id: 7, Mentee_id: 24, class_year:'2022-2023'},{Mentor_id: 8, Mentee_id: 24, class_year:'2022-2023'},
                                            {Mentor_id: 7, Mentee_id: 25, class_year:'2022-2023'},{Mentor_id: 8, Mentee_id: 25, class_year:'2022-2023'},
                                            {Mentor_id: 7, Mentee_id: 26, class_year:'2022-2023'},{Mentor_id: 8, Mentee_id: 26, class_year:'2022-2023'},
                                            {Mentor_id: 7, Mentee_id: 27, class_year:'2022-2023'},{Mentor_id: 8, Mentee_id: 27, class_year:'2022-2023'},
                                            {Mentor_id: 7, Mentee_id: 28, class_year:'2022-2023'},{Mentor_id: 8, Mentee_id: 28, class_year:'2022-2023'},
                                            {Mentor_id: 7, Mentee_id: 29, class_year:'2022-2023'},{Mentor_id: 8, Mentee_id: 29, class_year:'2022-2023'},
                                            {Mentor_id: 9, Mentee_id: 30, class_year:'2022-2023'},{Mentor_id: 10, Mentee_id: 30, class_year:'2022-2023'},
                                            {Mentor_id: 9, Mentee_id: 31, class_year:'2022-2023'},{Mentor_id: 10, Mentee_id: 31, class_year:'2022-2023'},
                                            {Mentor_id: 9, Mentee_id: 32, class_year:'2022-2023'},{Mentor_id: 10, Mentee_id: 32, class_year:'2022-2023'},
                                            {Mentor_id: 9, Mentee_id: 33, class_year:'2022-2023'},{Mentor_id: 10, Mentee_id: 33, class_year:'2022-2023'},
                                            {Mentor_id: 9, Mentee_id: 34, class_year:'2022-2023'},{Mentor_id: 10, Mentee_id: 34, class_year:'2022-2023'},
                                            {Mentor_id: 9, Mentee_id: 35, class_year:'2022-2023'},{Mentor_id: 10, Mentee_id: 35, class_year:'2022-2023'},
                                            {Mentor_id: 9, Mentee_id: 36, class_year:'2022-2023'},{Mentor_id: 10, Mentee_id: 36, class_year:'2022-2023'},
                                            {Mentor_id: 11, Mentee_id: 37, class_year:'2022-2023'},{Mentor_id: 12, Mentee_id: 37, class_year:'2022-2023'},
                                            {Mentor_id: 11, Mentee_id: 38, class_year:'2022-2023'},{Mentor_id: 12, Mentee_id: 38, class_year:'2022-2023'},
                                            {Mentor_id: 11, Mentee_id: 39, class_year:'2022-2023'},{Mentor_id: 12, Mentee_id: 39, class_year:'2022-2023'},
                                            {Mentor_id: 11, Mentee_id: 40, class_year:'2022-2023'},{Mentor_id: 12, Mentee_id: 40, class_year:'2022-2023'},
                                            {Mentor_id: 11, Mentee_id: 41, class_year:'2022-2023'},{Mentor_id: 12, Mentee_id: 41, class_year:'2022-2023'},
                                            {Mentor_id: 11, Mentee_id: 42, class_year:'2022-2023'},{Mentor_id: 12, Mentee_id: 42, class_year:'2022-2023'},
                                            {Mentor_id: 11, Mentee_id: 43, class_year:'2022-2023'},{Mentor_id: 12, Mentee_id: 43, class_year:'2022-2023'},
                                            {Mentor_id: 13, Mentee_id: 44, class_year:'2022-2023'},{Mentor_id: 14, Mentee_id: 44, class_year:'2022-2023'},
                                            {Mentor_id: 13, Mentee_id: 45, class_year:'2022-2023'},{Mentor_id: 14, Mentee_id: 45, class_year:'2022-2023'},
                                            {Mentor_id: 13, Mentee_id: 46, class_year:'2022-2023'},{Mentor_id: 14, Mentee_id: 46, class_year:'2022-2023'},
                                            {Mentor_id: 13, Mentee_id: 47, class_year:'2022-2023'},{Mentor_id: 14, Mentee_id: 47, class_year:'2022-2023'},
                                            {Mentor_id: 13, Mentee_id: 48, class_year:'2022-2023'},{Mentor_id: 14, Mentee_id: 48, class_year:'2022-2023'},
                                            {Mentor_id: 13, Mentee_id: 49, class_year:'2022-2023'},{Mentor_id: 14, Mentee_id: 49, class_year:'2022-2023'},
                                            {Mentor_id: 13, Mentee_id: 50, class_year:'2022-2023'},{Mentor_id: 14, Mentee_id: 50, class_year:'2022-2023'},
                                            {Mentor_id: 13, Mentee_id: 51, class_year:'2022-2023'},{Mentor_id: 14, Mentee_id: 51, class_year:'2022-2023'},
                                            {Mentor_id: 15, Mentee_id: 52, class_year:'2022-2023'},{Mentor_id: 16, Mentee_id: 52, class_year:'2022-2023'},
                                            {Mentor_id: 15, Mentee_id: 53, class_year:'2022-2023'},{Mentor_id: 16, Mentee_id: 53, class_year:'2022-2023'},
                                            {Mentor_id: 15, Mentee_id: 54, class_year:'2022-2023'},{Mentor_id: 16, Mentee_id: 54, class_year:'2022-2023'},
                                            {Mentor_id: 15, Mentee_id: 55, class_year:'2022-2023'},{Mentor_id: 16, Mentee_id: 55, class_year:'2022-2023'},
                                            {Mentor_id: 15, Mentee_id: 56, class_year:'2022-2023'},{Mentor_id: 16, Mentee_id: 56, class_year:'2022-2023'},
                                            {Mentor_id: 15, Mentee_id: 57, class_year:'2022-2023'},{Mentor_id: 16, Mentee_id: 57, class_year:'2022-2023'},
                                            {Mentor_id: 15, Mentee_id: 58, class_year:'2022-2023'},{Mentor_id: 16, Mentee_id: 58, class_year:'2022-2023'},
                                            {Mentor_id: 15, Mentee_id: 59, class_year:'2022-2023'},{Mentor_id: 16, Mentee_id: 59, class_year:'2022-2023'},
                                            {Mentor_id: 17, Mentee_id: 60, class_year:'2022-2023'},{Mentor_id: 18, Mentee_id: 60, class_year:'2022-2023'},
                                            {Mentor_id: 17, Mentee_id: 61, class_year:'2022-2023'},{Mentor_id: 18, Mentee_id: 61, class_year:'2022-2023'},
                                            {Mentor_id: 17, Mentee_id: 62, class_year:'2022-2023'},{Mentor_id: 18, Mentee_id: 62, class_year:'2022-2023'},
                                            {Mentor_id: 17, Mentee_id: 63, class_year:'2022-2023'},{Mentor_id: 18, Mentee_id: 63, class_year:'2022-2023'},
                                            {Mentor_id: 17, Mentee_id: 64, class_year:'2022-2023'},{Mentor_id: 18, Mentee_id: 64, class_year:'2022-2023'},
                                            {Mentor_id: 17, Mentee_id: 65, class_year:'2022-2023'},{Mentor_id: 18, Mentee_id: 65, class_year:'2022-2023'},
                                            {Mentor_id: 17, Mentee_id: 66, class_year:'2022-2023'},{Mentor_id: 18, Mentee_id: 66, class_year:'2022-2023'},
                                            {Mentor_id: 19, Mentee_id: 67, class_year:'2022-2023'},{Mentor_id: 20, Mentee_id: 67, class_year:'2022-2023'},
                                            {Mentor_id: 19, Mentee_id: 68, class_year:'2022-2023'},{Mentor_id: 20, Mentee_id: 68, class_year:'2022-2023'},
                                            {Mentor_id: 19, Mentee_id: 69, class_year:'2022-2023'},{Mentor_id: 20, Mentee_id: 69, class_year:'2022-2023'},
                                            {Mentor_id: 19, Mentee_id: 70, class_year:'2022-2023'},{Mentor_id: 20, Mentee_id: 70, class_year:'2022-2023'},
                                            {Mentor_id: 19, Mentee_id: 71, class_year:'2022-2023'},{Mentor_id: 20, Mentee_id: 71, class_year:'2022-2023'},
                                            {Mentor_id: 19, Mentee_id: 72, class_year:'2022-2023'},{Mentor_id: 20, Mentee_id: 72, class_year:'2022-2023'},
                                            {Mentor_id: 19, Mentee_id: 73, class_year:'2022-2023'},{Mentor_id: 20, Mentee_id: 73, class_year:'2022-2023'},
                                            {Mentor_id: 21, Mentee_id: 74, class_year:'2022-2023'},{Mentor_id: 22, Mentee_id: 74, class_year:'2022-2023'},
                                            {Mentor_id: 21, Mentee_id: 75, class_year:'2022-2023'},{Mentor_id: 22, Mentee_id: 75, class_year:'2022-2023'},
                                            {Mentor_id: 21, Mentee_id: 76, class_year:'2022-2023'},{Mentor_id: 22, Mentee_id: 76, class_year:'2022-2023'},
                                            {Mentor_id: 21, Mentee_id: 77, class_year:'2022-2023'},{Mentor_id: 22, Mentee_id: 77, class_year:'2022-2023'},
                                            {Mentor_id: 21, Mentee_id: 78, class_year:'2022-2023'},{Mentor_id: 22, Mentee_id: 78, class_year:'2022-2023'},
                                            {Mentor_id: 21, Mentee_id: 79, class_year:'2022-2023'},{Mentor_id: 22, Mentee_id: 79, class_year:'2022-2023'},
                                            {Mentor_id: 21, Mentee_id: 80, class_year:'2022-2023'},{Mentor_id: 22, Mentee_id: 80, class_year:'2022-2023'},
                                            {Mentor_id: 21, Mentee_id: 81, class_year:'2022-2023'},{Mentor_id: 22, Mentee_id: 81, class_year:'2022-2023'}])